version: '3'
services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - i-connect
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 5050:80
    networks:
      - i-connect
    restart: unless-stopped
  api:
    build:
      context: ./
      dockerfile: api/Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - i-connect
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./api:/opt/app/api
networks:
  i-connect:
volumes:
  data:
